import type { Metadata } from "next";
import { iransans } from "./fonts";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./component/templates/Header";
import {Footer} from "./component/templates/Footer"
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={iransans.className} 
    >
     <Header/>
      <body className={iransans.className} rounded-t-3 >
        <main className={iransans.className}>{children}</main>
      </body>
      <Footer />
    </html>
  );
}
