import type { Metadata } from "next";
import { iransans } from "./fonts";
import "./globals.css";
import { Header } from "./components/templates/Header";
import { Footer } from "./components/templates/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={iransans.className}>
      <body className={iransans.className}>
        <Header />
        <main className={iransans.className}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
